image: node:10.15.3

stages:
  - install_dependencies
  - test
  - sonar
  - build
  - deploy

install_dependencies:
  stage: install_dependencies
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
  script:
    - npm ci
  only:
    changes:
      - package-lock.json

test:
  stage: test
  script:
    - npm run test:unit -- --coverage
  coverage: '/All\sfiles.*?\s+(\d+.\d+)/'
  artifacts:
    paths:
      - ./coverage/lcov.info
    expire_in: 1 week
  only:
    - master
    - staging

SonarScanner:
  image: addianto/sonar-scanner-cli:latest
  stage: sonar
  script:
    - sonar-scanner
      -Dsonar.host.url=https://pmpl.cs.ui.ac.id/sonarqube
      -Dsonar.login=$SONARQUBE_TOKEN
      -Dsonar.projectKey=$SONARQUBE_PROJECT_KEY
      -Dsonar.branch.name=$CI_COMMIT_REF_NAME
  only:
    - master
    - staging
    - development
  dependencies:
    - test

build:
  stage: build
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run build
  artifacts:
    paths:
      - dist
    expire_in: 1 week
  only:
    - master
    - staging

deploy:
  stage: deploy
  script:
    - npm i -g netlify-cli
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod --timeout=900
  dependencies:
    - build
  only:
    - master
    - staging
